import { NuqsAdapter } from 'nuqs/adapters/next/app'
import type { Metadata } from 'next'
import { figtree, sentient, geistSans, geistMono } from '@/fonts'

import 'swiper/css'
import 'swiper/css/pagination'
import 'swiper/css/navigation'
import 'swiper/css/free-mode'
import './globals.css'

export const metadata: Metadata = {
  title: 'TrueKindKanva',
  description: 'Generated by true kind kanva'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} ${sentient.variable} antialiased`}
      >
        <NuqsAdapter>{children}</NuqsAdapter>
      </body>
    </html>
  )
}
