import 'swiper/css'
import 'swiper/css/pagination'
import 'swiper/css/navigation'
import 'swiper/css/free-mode'
import 'swiper/css/thumbs'
import './globals.css'

import type { Metadata } from 'next'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { figtree, sentient, geistSans, geistMono } from '@/fonts'
import { Toaster } from 'sonner'
import ReduxProvider from './redux-provider'
import Header from '@/components/header'
import CartPopup from '@/components/cart/CartPopup'
import Footer from '@/components/footer/Footer'

export const metadata: Metadata = {
  title: {
    template: '%s | True Kind Kanva',
    default: 'True Kind Kanva'
  },
  description: 'Generated by true kind kanva | True Kind Kanva',
  icons: {
    icon: '/favicon.ico'
  },
  robots: {
    index: true,
    follow: true
  }
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} ${sentient.variable} antialiased relative`}
      >
        <ReduxProvider>
          <Header />

          <NuqsAdapter>{children}</NuqsAdapter>

          <Footer />

          <CartPopup />
        </ReduxProvider>

        <Toaster />
      </body>
    </html>
  )
}
